Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "main"
  config.vm.provision "ansible", playbook: "ubuntu_init_vagrant.yml"
  config.vm.synced_folder "../src", "/home/vagrant/src"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end
  config.vm.network "public_network", ip:"192.168.5.137", bridge: [
      "wlp2s0",
      "enp1s0",
  ]

end
